const Items = [
  [
    {
      name: "빈칸",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 0],
      gold: 0,
      img: "shield-1.png",
    },
    {
      name: "나무 검",
      maxHp: 0,
      hp: 0,
      atk: 2,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 1],
      gold: 10,
      img: "weapon-1.png",
    },
    {
      name: "철 검",
      maxHp: 0,
      hp: 0,
      atk: 5,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 2],
      gold: 80,
      img: "weapon-2.png",
    },
    {
      name: "다이아몬드 검",
      maxHp: 0,
      hp: 0,
      atk: 10,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 3],
      gold: 500,
      img: "weapon-3.png",
    },
  ],
  [
    {
      name: "빈칸",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 0],
      gold: 0,
      img: "shield-1.png",
    },
    {
      name: "나무 방패",
      maxHp: 5,
      hp: 5,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [1, 1],
      gold: 10,
      img: "shield-1.png",
    },
    {
      name: "철 방패",
      maxHp: 15,
      hp: 15,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [1, 2],
      gold: 80,
      img: "shield-2.png",
    },
    {
      name: "다이아몬드 방패",
      maxHp: 30,
      hp: 30,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [1, 3],
      gold: 500,
      img: "shield-3.png",
    },
  ],
  [
    {
      name: "빈칸",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [0, 0],
      gold: 0,
      img: "shield-1.png",
    },
    {
      name: "나무 갑옷",
      maxHp: 2,
      hp: 2,
      atk: 1,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [2, 1],
      gold: 10,
      img: "amor-1.png",
    },
    {
      name: "철 갑옷",
      maxHp: 7,
      hp: 7,
      atk: 2,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [2, 2],
      gold: 80,
      img: "amor-2.png",
    },
    {
      name: "다이아몬드 갑옷",
      maxHp: 15,
      hp: 15,
      atk: 5,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [2, 3],
      gold: 500,
      img: "amor-3.png",
    },
  ],
  [
    {
      name: "빈칸",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [3, 0],
      gold: 0,
      img: "shield-1.png",
    },
    {
      name: "킹 슬라임의 왕관",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0.5,
      def_amp: 0,
      crit: 0,
      equip_info: [3, 1],
      gold: 0,
      img: "crown.png",
    },
  ],
  [
    {
      name: "빈칸",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0,
      crit: 0,
      equip_info: [4, 0],
      gold: 0,
      img: "shield-1.png",
    },
    {
      name: "언데드 골렘 조각 반지",
      maxHp: 0,
      hp: 0,
      atk: 0,
      atk_amp: 0,
      def_amp: 0.3,
      crit: 0,
      equip_info: [4, 1],
      gold: 0,
      img: "ring.png",
    },
  ],
];

export default Items;
